-- 코드를 입력하세요
# SELECT INFO.INGREDIENT_TYPE, SUM(FH.TOTAL_ORDER) AS TOTAL_ORDER
SELECT INFO.INGREDIENT_TYPE, SUM(FH.TOTAL_ORDER)
FROM FIRST_HALF AS FH, ICECREAM_INFO AS INFO
WHERE FH.FLAVOR = INFO.FLAVOR
GROUP BY INFO.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER